<?php
/**
	* --------------------------------------------------------------------------
	*	@author			Hossein Mohammadi Maklavani
	*	@copyright		Copyright (C) 2014 - 2016 Digarsoo. All rights reserved.
	*	creation date	12/04/2015
	*	last edit		12/04/2015
	* --------------------------------------------------------------------------
*/

defined('_ALLOW') or die("access denied!");

class File extends System {
	private $filename;
	private $setting;

	function __construct($src)
	{
		$this->filename = $src;

		if(System::has_file($this->filename . '.' . _COPR))
			$this->setting = json_decode(file_get_contents(_SRC . $this->filename . '.' . _COPR));
		else
		{
			$this->setting = new stdClass();
			$this->setting->permission = 5;
			$this->setting->downloads = 0;
			$this->setting->deleted = 1;
			$this->setting->users = array('-1');

			$file = fopen(_SRC . $this->filename . '.' . _COPR , "w");
			fwrite($file , json_encode($this->setting , JSON_PRETTY_PRINT));
			fclose($file);
		}
	}

	public function is_readable()
	{
		if(User::has_permission($this->setting->permission) && $this->has_users())
			return true;
		return false;
	}

	private function has_users()
	{
		if(in_array('-1' , $this->setting->users) || in_array(User::$code , $this->setting->users))
			return true;
		return false;
	}

	public function read_file()
	{
		$this->setting->downloads++;

		$file = fopen(_SRC . $this->filename . '.' . _COPR , "w");
		fwrite($file , json_encode($this->setting , JSON_PRETTY_PRINT));
		fclose($file);

		$dot_pos = strrpos($this->filename , '.' , -1);
		$type = substr($this->filename , $dot_pos - strlen($this->filename) + 1);

		if($mime = $this->get_mime_type($type))
			header('Content-type: ' . $mime);
		else
		{
			header('Content-Description: File Transfer');
			header('Content-Type: application/octet-stream');
			header('Expires: 0');
			header('Cache-Control: must-revalidate');
			header('Pragma: public');
		}

		$this->public_headers();
		readfile($this->filename);
		die();
	}

	private function public_headers()
	{
		header('Content-Disposition: inline; filename=' . basename($this->filename));
		header('Content-Length: ' . filesize($this->filename));
		header('Content-Transfer-Encoding: binary');
	}

	private function get_mime_type($type)
	{
		switch ($type){
			case "dxf": return "image/vnd.dxf";
			case "bmp": return "image/bmp";
			case "btif": return "image/prs.btif";
			case "sub": return "image/vnd.dvb.subtitle";
			case "ras": return "image/x-cmu-raster";
			case "cgm": return "image/cgm";
			case "cmx": return "image/x-cmx";
			case "uvi": return "image/vnd.dece.graphic";
			case "djvu": return "image/vnd.djvu";
			case "dwg": return "image/vnd.dwg";
			case "mmr": return "image/vnd.fujixerox.edmics-mmr";
			case "rlc": return "image/vnd.fujixerox.edmics-rlc";
			case "xif": return "image/vnd.xiff";
			case "fst": return "image/vnd.fst";
			case "fbs": return "image/vnd.fastbidsheet";
			case "fpx": return "image/vnd.fpx";
			case "npx": return "image/vnd.net-fpx";
			case "fh": return "image/x-freehand";
			case "g3": return "image/g3fax";
			case "gif": return "image/gif";
			case "ico": return "image/x-icon";
			case "ief": return "image/ief";
			case "jpeg": return "image/jpeg";
			case "jpg": return "image/jpeg";
			case "mdi": return "image/vnd.ms-modi";
			case "ktx": return "image/ktx";
			case "pcx": return "image/x-pcx";
			case "psd": return "image/vnd.adobe.photoshop";
			case "pic": return "image/x-pict";
			case "pnm": return "image/x-portable-anymap";
			case "pbm": return "image/x-portable-bitmap";
			case "pgm": return "image/x-portable-graymap";
			case "png": return "image/png";
			case "ppm": return "image/x-portable-pixmap";
			case "svg": return "image/svg+xml";
			case "rgb": return "image/x-rgb";
			case "tiff": return "image/tiff";
			case "wbmp": return "image/vnd.wap.wbmp";
			case "webp": return "image/webp";
			case "xbm": return "image/x-xbitmap";
			case "xpm": return "image/x-xpixmap";
			case "xwd": return "image/x-xwindowdump";
			case "3gp": return "video/3gpp";
			case "3g2": return "video/3gpp2";
			case "avi": return "video/x-msvideo";
			case "uvh": return "video/vnd.dece.hd";
			case "uvm": return "video/vnd.dece.mobile";
			case "uvu": return "video/vnd.uvvu.mp4";
			case "uvp": return "video/vnd.dece.pd";
			case "uvs": return "video/vnd.dece.sd";
			case "uvv": return "video/vnd.dece.video";
			case "fvt": return "video/vnd.fvt";
			case "f4v": return "video/x-f4v";
			case "flv": return "video/x-flv";
			case "fli": return "video/x-fli";
			case "h261": return "video/h261";
			case "h263": return "video/h263";
			case "h264": return "video/h264";
			case "jpm": return "video/jpm";
			case "jpgv": return "video/jpeg";
			case "m4v": return "video/x-m4v";
			case "asf": return "video/x-ms-asf";
			case "pyv": return "video/vnd.ms-playready.media.pyv";
			case "wm": return "video/x-ms-wm";
			case "wmx": return "video/x-ms-wmx";
			case "wmv": return "video/x-ms-wmv";
			case "wvx": return "video/x-ms-wvx";
			case "mj2": return "video/mj2";
			case "mxu": return "video/vnd.mpegurl";
			case "mpeg": return "video/mpeg";
			case "mp4": return "video/mp4";
			case "ogv": return "video/ogg";
			case "webm": return "video/webm";
			case "qt": return "video/quicktime";
			case "movie": return "video/x-sgi-movie";
			case "viv": return "video/vnd.vivo";
			case "adp": return "audio/adpcm";
			case "aac": return "audio/x-aac";
			case "aif": return "audio/x-aiff";
			case "uva": return "audio/vnd.dece.audio";
			case "eol": return "audio/vnd.digital-winds";
			case "dra": return "audio/vnd.dra";
			case "dts": return "audio/vnd.dts";
			case "dtshd": return "audio/vnd.dts.hd";
			case "rip": return "audio/vnd.rip";
			case "lvp": return "audio/vnd.lucent.voice";
			case "m3u": return "audio/x-mpegurl";
			case "pya": return "audio/vnd.ms-playready.media.pya";
			case "wma": return "audio/x-ms-wma";
			case "wax": return "audio/x-ms-wax";
			case "mid": return "audio/midi";
			case "mpga": return "audio/mpeg";
			case "mp4a": return "audio/mp4";
			case "ecelp4800": return "audio/vnd.nuera.ecelp4800";
			case "ecelp7470": return "audio/vnd.nuera.ecelp7470";
			case "ecelp9600": return "audio/vnd.nuera.ecelp9600";
			case "oga": return "audio/ogg";
			case "weba": return "audio/webm";
			case "ram": return "audio/x-pn-realaudio";
			case "rmp": return "audio/x-pn-realaudio-plugin";
			case "au": return "audio/basic";
			case "wav": return "audio/x-wav";
			case "s": return "text/x-asm";
			case "par": return "text/plain-bas";
			case "c": return "text/x-c";
			case "css": return "text/css";
			case "csv": return "text/csv";
			case "curl": return "text/vnd.curl";
			case "dcurl": return "text/vnd.curl.dcurl";
			case "mcurl": return "text/vnd.curl.mcurl";
			case "scurl": return "text/vnd.curl.scurl";
			case "flx": return "text/vnd.fmi.flexstor";
			case "f": return "text/x-fortran";
			case "gv": return "text/vnd.graphviz";
			case "html": return "text/html";
			case "ics": return "text/calendar";
			case "3dml": return "text/vnd.in3d.3dml";
			case "spot": return "text/vnd.in3d.spot";
			case "jad": return "text/vnd.sun.j2me.app-descriptor";
			case "java": return "text/x-java-source,java";
			case "fly": return "text/vnd.fly";
			case "n3": return "text/n3";
			case "p": return "text/x-pascal";
			case "dsc": return "text/prs.lines.tag";
			case "rtx": return "text/richtext";
			case "etx": return "text/x-setext";
			case "sgml": return "text/sgml";
			case "tsv": return "text/tab-separated-values";
			case "txt": return "text/plain";
			case "t": return "text/troff";
			case "ttl": return "text/turtle";
			case "uri": return "text/uri-list";
			case "uu": return "text/x-uuencode";
			case "vcs": return "text/x-vcalendar";
			case "vcf": return "text/x-vcard";
			case "wml": return "text/vnd.wap.wml";
			case "wmls": return "text/vnd.wap.wmlscript";
			case "yaml": return "text/yaml";
			case "dwf": return "model/vnd.dwf";
			case "dae": return "model/vnd.collada+xml";
			case "gtw": return "model/vnd.gtw";
			case "gdl": return "model/vnd.gdl";
			case "igs": return "model/iges";
			case "msh": return "model/mesh";
			case "wrl": return "model/vrml";
			case "mts": return "model/vnd.mts";
			case "vtu": return "model/vnd.vtu";
			case "pdf": return "application/pdf";
			case "aw": return "application/applixware";
			case "atomcat": return "application/atomcat+xml";
			case "atomsvc": return "application/atomsvc+xml";
			case "atom": return "application/atom+xml";
			case "ac": return "application/pkix-attr-cert";
			case "bin": return "application/octet-stream";
			case "cdx": return "chemical/x-cdx";
			case "cml": return "chemical/x-cml";
			case "csml": return "chemical/x-csml";
			case "cdmia": return "application/cdmi-capability";
			case "cdmic": return "application/cdmi-container";
			case "cdmid": return "application/cdmi-domain";
			case "cdmio": return "application/cdmi-object";
			case "cdmiq": return "application/cdmi-queue";
			case "cpt": return "application/mac-compactpro";
			case "ice": return "x-conference/x-cooltalk";
			case "cif": return "chemical/x-cif";
			case "cmdf": return "chemical/x-cmdf";
			case "cu": return "application/cu-seeme";
			case "cww": return "application/prs.cww";
			case "dssc": return "application/dssc+der";
			case "xdssc": return "application/dssc+xml";
			case "es": return "application/ecmascript";
			case "exi": return "application/exi";
			case "epub": return "application/epub+zip";
			case "eml": return "message/rfc822";
			case "emma": return "application/emma+xml";
			case "stk": return "application/hyperstudio";
			case "rif": return "application/reginfo+xml";
			case "ipfix": return "application/ipfix";
			case "cer": return "application/pkix-cert";
			case "pki": return "application/pkixcmp";
			case "crl": return "application/pkix-crl";
			case "pkipath": return "application/pkix-pkipath";
			case "jar": return "application/java-archive";
			case "class": return "application/java-vm";
			case "ser": return "application/java-serialized-object";
			case "js": return "application/javascript";
			case "json": return "application/json";
			case "hqx": return "application/mac-binhex40";
			case "mrc": return "application/marc";
			case "mrcx": return "application/marcxml+xml";
			case "mxf": return "application/mxf";
			case "ma": return "application/mathematica";
			case "mathml": return "application/mathml+xml";
			case "mbox": return "application/mbox";
			case "mscml": return "application/mediaservercontrol+xml";
			case "mads": return "application/mads+xml";
			case "mets": return "application/mets+xml";
			case "mods": return "application/mods+xml";
			case "meta4": return "application/metalink4+xml";
			case "onetoc": return "application/onenote";
			case "doc": return "application/msword";
			case "m21": return "application/mp21";
			case "mp4": return "application/mp4";
			case "oda": return "application/oda";
			case "ogx": return "application/ogg";
			case "opf": return "application/oebps-package+xml";
			case "prf": return "application/pics-rules";
			case "p10": return "application/pkcs10";
			case "p7m": return "application/pkcs7-mime";
			case "p7s": return "application/pkcs7-signature";
			case "p8": return "application/pkcs8";
			case "pfr": return "application/font-tdpfr";
			case "pskcxml": return "application/pskc+xml";
			case "ai": return "application/postscript";
			case "pgp": return "application/pgp-signature";
			case "pls": return "application/pls+xml";
			case "rsd": return "application/rsd+xml";
			case "rnc": return "application/relax-ng-compact-syntax";
			case "rdf": return "application/rdf+xml";
			case "rtf": return "application/rtf";
			case "rss": return "application/rss+xml";
			case "shf": return "application/shf+xml";
			case "sru": return "application/sru+xml";
			case "setpay": return "application/set-payment-initiation";
			case "setreg": return "application/set-registration-initiation";
			case "spq": return "application/scvp-vp-request";
			case "spp": return "application/scvp-vp-response";
			case "scq": return "application/scvp-cv-request";
			case "scs": return "application/scvp-cv-response";
			case "sdp": return "application/sdp";
			case "tfi": return "application/thraud+xml";
			case "rq": return "application/sparql-query";
			case "srx": return "application/sparql-results+xml";
			case "gram": return "application/srgs";
			case "grxml": return "application/srgs+xml";
			case "ssml": return "application/ssml+xml";
			case "smi": return "application/smil+xml";
			case "sbml": return "application/sbml+xml";
			case "tei": return "application/tei+xml";
			case "tsd": return "application/timestamped-data";
			case "ccxml": return "application/ccxml+xml,";
			case "vxml": return "application/voicexml+xml";
			case "davmount": return "application/davmount+xml";
			case "wspolicy": return "application/wspolicy+xml";
			case "wgt": return "application/widget";
			case "hlp": return "application/winhlp";
			case "wsdl": return "application/wsdl+xml";
			case "xer": return "application/patch-ops-error+xml";
			case "rl": return "application/resource-lists+xml";
			case "rs": return "application/rls-services+xml";
			case "rld": return "application/resource-lists-diff+xml";
			case "xyz": return "chemical/x-xyz";
			case "yang": return "application/yang";
			case "yin": return "application/yin+xml";
			case "zip": return "application/zip";
			case "7z": return "application/x-7z-compressed";
			case "abw": return "application/x-abiword";
			case "ace": return "application/x-ace-compressed";
			case "aab": return "application/x-authorware-bin";
			case "aam": return "application/x-authorware-map";
			case "aas": return "application/x-authorware-seg";
			case "swf": return "application/x-shockwave-flash";
			case "dir": return "application/x-director";
			case "bcpio": return "application/x-bcpio";
			case "torrent": return "application/x-bittorrent";
			case "sh": return "application/x-sh";
			case "bz": return "application/x-bzip";
			case "bz2": return "application/x-bzip2";
			case "csh": return "application/x-csh";
			case "cpio": return "application/x-cpio";
			case "deb": return "application/x-debian-package";
			case "dvi": return "application/x-dvi";
			case "dtb": return "application/x-dtbook+xml";
			case "res": return "application/x-dtbresource+xml";
			case "dtd": return "application/xml-dtd";
			case "wad": return "application/x-doom";
			case "spl": return "application/x-futuresplash";
			case "gsf": return "application/x-font-ghostscript";
			case "bdf": return "application/x-font-bdf";
			case "gtar": return "application/x-gtar";
			case "texinfo": return "application/x-texinfo";
			case "gnumeric": return "application/x-gnumeric";
			case "hdf": return "application/x-hdf";
			case "jnlp": return "application/x-java-jnlp-file";
			case "latex": return "application/x-latex";
			case "mdb": return "application/x-msaccess";
			case "exe": return "application/x-msdownload";
			case "application": return "application/x-ms-application";
			case "clp": return "application/x-msclip";
			case "crd": return "application/x-mscardfile";
			case "mvb": return "application/x-msmediaview";
			case "mny": return "application/x-msmoney";
			case "obd": return "application/x-msbinder";
			case "pub": return "application/x-mspublisher";
			case "scd": return "application/x-msschedule";
			case "xap": return "application/x-silverlight-app";
			case "wmd": return "application/x-ms-wmd";
			case "wmz": return "application/x-ms-wmz";
			case "wmf": return "application/x-msmetafile";
			case "trm": return "application/x-msterminal";
			case "wri": return "application/x-mswrite";
			case "xbap": return "application/x-ms-xbap";
			case "prc": return "application/x-mobipocket-ebook";
			case "mxml": return "application/xv+xml";
			case "ncx": return "application/x-dtbncx+xml";
			case "nc": return "application/x-netcdf";
			case "otf": return "application/x-font-otf";
			case "chat": return "application/x-chat";
			case "p12": return "application/x-pkcs12";
			case "p7r": return "application/x-pkcs7-certreqresp";
			case "p7b": return "application/x-pkcs7-certificates";
			case "pcf": return "application/x-font-pcf";
			case "pgn": return "application/x-chess-pgn";
			case "pfa": return "application/x-font-type1";
			case "psf": return "application/x-font-linux-psf";
			case "rar": return "application/x-rar-compressed";
			case "snf": return "application/x-font-snf";
			case "shar": return "application/x-shar";
			case "sit": return "application/x-stuffit";
			case "sitx": return "application/x-stuffitx";
			case "sv4cpio": return "application/x-sv4cpio";
			case "sv4crc": return "application/x-sv4crc";
			case "tar": return "application/x-tar";
			case "tcl": return "application/x-tcl";
			case "tex": return "application/x-tex";
			case "tfm": return "application/x-tex-tfm";
			case "ttf": return "application/x-font-ttf";
			case "ustar": return "application/x-ustar";
			case "vcd": return "application/x-cdlink";
			case "src": return "application/x-wais-source";
			case "woff": return "application/x-font-woff";
			case "der": return "application/x-x509-ca-cert";
			case "fig": return "application/x-xfig";
			case "xhtml": return "application/xhtml+xml";
			case "xml": return "application/xml";
			case "xdf": return "application/xcap-diff+xml";
			case "xenc": return "application/xenc+xml";
			case "xslt": return "application/xslt+xml";
			case "xop": return "application/xop+xml";
			case "xpi": return "application/x-xpinstall";
			case "xspf": return "application/xspf+xml";
			case "x3d": return "application/vnd.hzn-3d-crossword";
			case "mseq": return "application/vnd.mseq";
			case "pwn": return "application/vnd.3m.post-it-notes";
			case "plb": return "application/vnd.3gpp.pic-bw-large";
			case "psb": return "application/vnd.3gpp.pic-bw-small";
			case "pvb": return "application/vnd.3gpp.pic-bw-var";
			case "tcap": return "application/vnd.3gpp2.tcap";
			case "acc": return "application/vnd.americandynamics.acc";
			case "acu": return "application/vnd.acucobol";
			case "atc": return "application/vnd.acucorp";
			case "air": return "application/vnd.adobe.air-application-installer-package+zip";
			case "fxp": return "application/vnd.adobe.fxp";
			case "ppd": return "application/vnd.cups-ppd";
			case "xdp": return "application/vnd.adobe.xdp+xml";
			case "xfdf": return "application/vnd.adobe.xfdf";
			case "ahead": return "application/vnd.ahead.space";
			case "azf": return "application/vnd.airzip.filesecure.azf";
			case "azs": return "application/vnd.airzip.filesecure.azs";
			case "azw": return "application/vnd.amazon.ebook";
			case "ami": return "application/vnd.amiga.ami";
			case "apk": return "application/vnd.android.package-archive";
			case "cii": return "application/vnd.anser-web-certificate-issue-initiation";
			case "fti": return "application/vnd.anser-web-funds-transfer-initiation";
			case "atx": return "application/vnd.antix.game-component";
			case "mpkg": return "application/vnd.apple.installer+xml";
			case "les": return "application/vnd.hhe.lesson-player";
			case "swi": return "application/vnd.aristanetworks.swi";
			case "aep": return "application/vnd.audiograph";
			case "cod": return "application/vnd.rim.cod";
			case "mpm": return "application/vnd.blueice.multipass";
			case "bmi": return "application/vnd.bmi";
			case "rep": return "application/vnd.businessobjects";
			case "cdxml": return "application/vnd.chemdraw+xml";
			case "cdbcmsg": return "application/vnd.contact.cmsg";
			case "cla": return "application/vnd.claymore";
			case "c4g": return "application/vnd.clonk.c4group";
			case "c11amc": return "application/vnd.cluetrust.cartomobile-config";
			case "c11amz": return "application/vnd.cluetrust.cartomobile-config-pkg";
			case "wmlc": return "application/vnd.wap.wmlc";
			case "xar": return "application/vnd.xara";
			case "cmc": return "application/vnd.cosmocaller";
			case "clkx": return "application/vnd.crick.clicker";
			case "clkk": return "application/vnd.crick.clicker.keyboard";
			case "clkp": return "application/vnd.crick.clicker.palette";
			case "clkt": return "application/vnd.crick.clicker.template";
			case "clkw": return "application/vnd.crick.clicker.wordbank";
			case "wbs": return "application/vnd.criticaltools.wbs+xml";
			case "cryptonote": return "application/vnd.rig.cryptonote";
			case "car": return "application/vnd.curl.car";
			case "pcurl": return "application/vnd.curl.pcurl";
			case "cmp": return "application/vnd.yellowriver-custom-menu";
			case "seed": return "application/vnd.fdsn.seed";
			case "ait": return "application/vnd.dvb.ait";
			case "svc": return "application/vnd.dvb.service";
			case "mlp": return "application/vnd.dolby.mlp";
			case "dpg": return "application/vnd.dpgraph";
			case "dfac": return "application/vnd.dreamfactory";
			case "geo": return "application/vnd.dynageo";
			case "mag": return "application/vnd.ecowin.chart";
			case "mgz": return "application/vnd.proteus.magazine";
			case "nml": return "application/vnd.enliven";
			case "xpr": return "application/vnd.is-xpr";
			case "xfdl": return "application/vnd.xfdl";
			case "ez2": return "application/vnd.ezpix-album";
			case "ez3": return "application/vnd.ezpix-package";
			case "fe_launch": return "application/vnd.denovo.fcselayout-link";
			case "ftc": return "application/vnd.fluxtime.clip";
			case "fdf": return "application/vnd.fdf";
			case "mif": return "application/vnd.mif";
			case "fm": return "application/vnd.framemaker";
			case "fsc": return "application/vnd.fsc.weblaunch";
			case "fnc": return "application/vnd.frogans.fnc";
			case "ltf": return "application/vnd.frogans.ltf";
			case "ddd": return "application/vnd.fujixerox.ddd";
			case "xdw": return "application/vnd.fujixerox.docuworks";
			case "xbd": return "application/vnd.fujixerox.docuworks.binder";
			case "oas": return "application/vnd.fujitsu.oasys";
			case "oa2": return "application/vnd.fujitsu.oasys2";
			case "oa3": return "application/vnd.fujitsu.oasys3";
			case "fg5": return "application/vnd.fujitsu.oasysgp";
			case "bh2": return "application/vnd.fujitsu.oasysprs";
			case "fzs": return "application/vnd.fuzzysheet";
			case "gmx": return "application/vnd.gmx";
			case "txd": return "application/vnd.genomatix.tuxedo";
			case "ggb": return "application/vnd.geogebra.file";
			case "ggt": return "application/vnd.geogebra.tool";
			case "gex": return "application/vnd.geometry-explorer";
			case "gxt": return "application/vnd.geonext";
			case "g2w": return "application/vnd.geoplan";
			case "g3w": return "application/vnd.geospace";
			case "kml": return "application/vnd.google-earth.kml+xml";
			case "kmz": return "application/vnd.google-earth.kmz";
			case "gqf": return "application/vnd.grafeq";
			case "gac": return "application/vnd.groove-account";
			case "ghf": return "application/vnd.groove-help";
			case "gim": return "application/vnd.groove-identity-message";
			case "grv": return "application/vnd.groove-injector";
			case "gtm": return "application/vnd.groove-tool-message";
			case "tpl": return "application/vnd.groove-tool-template";
			case "vcg": return "application/vnd.groove-vcard";
			case "hpid": return "application/vnd.hp-hpid";
			case "hps": return "application/vnd.hp-hps";
			case "hbci": return "application/vnd.hbci";
			case "jlt": return "application/vnd.hp-jlyt";
			case "pcl": return "application/vnd.hp-pcl";
			case "hpgl": return "application/vnd.hp-hpgl";
			case "hvs": return "application/vnd.yamaha.hv-script";
			case "hvd": return "application/vnd.yamaha.hv-dic";
			case "hvp": return "application/vnd.yamaha.hv-voice";
			case "sfd-hdstx": return "application/vnd.hydrostatix.sof-data";
			case "hal": return "application/vnd.hal+xml";
			case "irm": return "application/vnd.ibm.rights-management";
			case "sc": return "application/vnd.ibm.secure-container";
			case "icc": return "application/vnd.iccprofile";
			case "igl": return "application/vnd.igloader";
			case "ivp": return "application/vnd.immervision-ivp";
			case "ivu": return "application/vnd.immervision-ivu";
			case "i2g": return "application/vnd.intergeo";
			case "cdy": return "application/vnd.cinderella";
			case "xpw": return "application/vnd.intercon.formnet";
			case "fcs": return "application/vnd.isac.fcs";
			case "igm": return "application/vnd.insors.igm";
			case "rcprofile": return "application/vnd.ipunplugged.rcprofile";
			case "irp": return "application/vnd.irepository.package+xml";
			case "joda": return "application/vnd.joost.joda-archive";
			case "ktz": return "application/vnd.kahootz";
			case "mmd": return "application/vnd.chipnuts.karaoke-mmd";
			case "karbon": return "application/vnd.kde.karbon";
			case "chrt": return "application/vnd.kde.kchart";
			case "kfo": return "application/vnd.kde.kformula";
			case "flw": return "application/vnd.kde.kivio";
			case "kon": return "application/vnd.kde.kontour";
			case "kpr": return "application/vnd.kde.kpresenter";
			case "ksp": return "application/vnd.kde.kspread";
			case "kwd": return "application/vnd.kde.kword";
			case "htke": return "application/vnd.kenameaapp";
			case "kia": return "application/vnd.kidspiration";
			case "kne": return "application/vnd.kinar";
			case "sse": return "application/vnd.kodak-descriptor";
			case "lasxml": return "application/vnd.las.las+xml";
			case "lbd": return "application/vnd.llamagraphics.life-balance.desktop";
			case "lbe": return "application/vnd.llamagraphics.life-balance.exchange+xml";
			case "jam": return "application/vnd.jam";
			case "123": return "application/vnd.lotus-1-2-3";
			case "apr": return "application/vnd.lotus-approach";
			case "pre": return "application/vnd.lotus-freelance";
			case "nsf": return "application/vnd.lotus-notes";
			case "org": return "application/vnd.lotus-organizer";
			case "scm": return "application/vnd.lotus-screencam";
			case "lwp": return "application/vnd.lotus-wordpro";
			case "portpkg": return "application/vnd.macports.portpkg";
			case "mgp": return "application/vnd.osgeo.mapguide.package";
			case "nbp": return "application/vnd.wolfram.player";
			case "mc1": return "application/vnd.medcalcdata";
			case "cdkey": return "application/vnd.mediastation.cdkey";
			case "mwf": return "application/vnd.mfer";
			case "mfm": return "application/vnd.mfmp";
			case "potm": return "application/vnd.ms-powerpoint.template.macroenabled.12";
			case "docm": return "application/vnd.ms-word.document.macroenabled.12";
			case "dotm": return "application/vnd.ms-word.template.macroenabled.12";
			case "mcd": return "application/vnd.mcd";
			case "flo": return "application/vnd.micrografx.flo";
			case "igx": return "application/vnd.micrografx.igx";
			case "es3": return "application/vnd.eszigno3+xml";
			case "cil": return "application/vnd.ms-artgalry";
			case "cab": return "application/vnd.ms-cab-compressed";
			case "ims": return "application/vnd.ms-ims";
			case "eot": return "application/vnd.ms-fontobject";
			case "xls": return "application/vnd.ms-excel";
			case "xlam": return "application/vnd.ms-excel.addin.macroenabled.12";
			case "xlsb": return "application/vnd.ms-excel.sheet.binary.macroenabled.12";
			case "xltm": return "application/vnd.ms-excel.template.macroenabled.12";
			case "xlsm": return "application/vnd.ms-excel.sheet.macroenabled.12";
			case "chm": return "application/vnd.ms-htmlhelp";
			case "lrm": return "application/vnd.ms-lrm";
			case "pptx": return "application/vnd.openxmlformats-officedocument.presentationml.presentation";
			case "sldx": return "application/vnd.openxmlformats-officedocument.presentationml.slide";
			case "ppsx": return "application/vnd.openxmlformats-officedocument.presentationml.slideshow";
			case "potx": return "application/vnd.openxmlformats-officedocument.presentationml.template";
			case "xlsx": return "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
			case "xltx": return "application/vnd.openxmlformats-officedocument.spreadsheetml.template";
			case "docx": return "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
			case "dotx": return "application/vnd.openxmlformats-officedocument.wordprocessingml.template";
			case "thmx": return "application/vnd.ms-officetheme";
			case "ppt": return "application/vnd.ms-powerpoint";
			case "ppam": return "application/vnd.ms-powerpoint.addin.macroenabled.12";
			case "sldm": return "application/vnd.ms-powerpoint.slide.macroenabled.12";
			case "pptm": return "application/vnd.ms-powerpoint.presentation.macroenabled.12";
			case "ppsm": return "application/vnd.ms-powerpoint.slideshow.macroenabled.12";
			case "mpp": return "application/vnd.ms-project";
			case "stl": return "application/vnd.ms-pki.stl";
			case "cat": return "application/vnd.ms-pki.seccat";
			case "vsd": return "application/vnd.visio";
			case "wpl": return "application/vnd.ms-wpl";
			case "wps": return "application/vnd.ms-works";
			case "xps": return "application/vnd.ms-xpsdocument";
			case "mpy": return "application/vnd.ibm.minipay";
			case "afp": return "application/vnd.ibm.modcap";
			case "rms": return "application/vnd.jcp.javame.midlet-rms";
			case "tmo": return "application/vnd.tmobile-livetv";
			case "mbk": return "application/vnd.mobius.mbk";
			case "dis": return "application/vnd.mobius.dis";
			case "plc": return "application/vnd.mobius.plc";
			case "mqy": return "application/vnd.mobius.mqy";
			case "msl": return "application/vnd.mobius.msl";
			case "txf": return "application/vnd.mobius.txf";
			case "daf": return "application/vnd.mobius.daf";
			case "mpc": return "application/vnd.mophun.certificate";
			case "mpn": return "application/vnd.mophun.application";
			case "m3u8": return "application/vnd.apple.mpegurl";
			case "mus": return "application/vnd.musician";
			case "msty": return "application/vnd.muvee.style";
			case "ngdat": return "application/vnd.nokia.n-gage.data";
			case "n-gage": return "application/vnd.nokia.n-gage.symbian.install";
			case "nlu": return "application/vnd.neurolanguage.nlu";
			case "dna": return "application/vnd.dna";
			case "nnd": return "application/vnd.noblenet-directory";
			case "nns": return "application/vnd.noblenet-sealer";
			case "nnw": return "application/vnd.noblenet-web";
			case "rpst": return "application/vnd.nokia.radio-preset";
			case "rpss": return "application/vnd.nokia.radio-presets";
			case "edm": return "application/vnd.novadigm.edm";
			case "edx": return "application/vnd.novadigm.edx";
			case "ext": return "application/vnd.novadigm.ext";
			case "gph": return "application/vnd.flographit";
			case "dd2": return "application/vnd.oma.dd2+xml";
			case "oth": return "application/vnd.oasis.opendocument.text-web";
			case "qbo": return "application/vnd.intu.qbo";
			case "oxt": return "application/vnd.openofficeorg.extension";
			case "osf": return "application/vnd.yamaha.openscoreformat";
			case "odc": return "application/vnd.oasis.opendocument.chart";
			case "otc": return "application/vnd.oasis.opendocument.chart-template";
			case "odb": return "application/vnd.oasis.opendocument.database";
			case "odf": return "application/vnd.oasis.opendocument.formula";
			case "odft": return "application/vnd.oasis.opendocument.formula-template";
			case "odg": return "application/vnd.oasis.opendocument.graphics";
			case "otg": return "application/vnd.oasis.opendocument.graphics-template";
			case "odi": return "application/vnd.oasis.opendocument.image";
			case "oti": return "application/vnd.oasis.opendocument.image-template";
			case "odp": return "application/vnd.oasis.opendocument.presentation";
			case "otp": return "application/vnd.oasis.opendocument.presentation-template";
			case "ods": return "application/vnd.oasis.opendocument.spreadsheet";
			case "ots": return "application/vnd.oasis.opendocument.spreadsheet-template";
			case "odt": return "application/vnd.oasis.opendocument.text";
			case "odm": return "application/vnd.oasis.opendocument.text-master";
			case "ott": return "application/vnd.oasis.opendocument.text-template";
			case "sxc": return "application/vnd.sun.xml.calc";
			case "stc": return "application/vnd.sun.xml.calc.template";
			case "sxd": return "application/vnd.sun.xml.draw";
			case "std": return "application/vnd.sun.xml.draw.template";
			case "sxi": return "application/vnd.sun.xml.impress";
			case "sti": return "application/vnd.sun.xml.impress.template";
			case "sxm": return "application/vnd.sun.xml.math";
			case "sxw": return "application/vnd.sun.xml.writer";
			case "sxg": return "application/vnd.sun.xml.writer.global";
			case "stw": return "application/vnd.sun.xml.writer.template";
			case "osfpvg": return "application/vnd.yamaha.openscoreformat.osfpvg+xml";
			case "dp": return "application/vnd.osgi.dp";
			case "pdb": return "application/vnd.palm";
			case "paw": return "application/vnd.pawaafile";
			case "pclxl": return "application/vnd.hp-pclxl";
			case "efif": return "application/vnd.picsel";
			case "plf": return "application/vnd.pocketlearn";
			case "pml": return "application/vnd.ctc-posml";
			case "pbd": return "application/vnd.powerbuilder6";
			case "box": return "application/vnd.previewsystems.box";
			case "ptid": return "application/vnd.pvi.ptid1";
			case "str": return "application/vnd.pg.format";
			case "ei6": return "application/vnd.pg.osasli";
			case "qps": return "application/vnd.publishare-delta-tree";
			case "wg": return "application/vnd.pmi.widget";
			case "qxd": return "application/vnd.quark.quarkxpress";
			case "esf": return "application/vnd.epson.esf";
			case "msf": return "application/vnd.epson.msf";
			case "ssf": return "application/vnd.epson.ssf";
			case "qam": return "application/vnd.epson.quickanime";
			case "qfx": return "application/vnd.intu.qfx";
			case "rm": return "application/vnd.rn-realmedia";
			case "bed": return "application/vnd.realvnc.bed";
			case "mxl": return "application/vnd.recordare.musicxml";
			case "musicxml": return "application/vnd.recordare.musicxml+xml";
			case "rdz": return "application/vnd.data-vision.rdz";
			case "rp9": return "application/vnd.cloanto.rp9";
			case "jisp": return "application/vnd.jisp";
			case "link66": return "application/vnd.route66.link66+xml";
			case "st": return "application/vnd.sailingtracker.track";
			case "sus": return "application/vnd.sus-calendar";
			case "sema": return "application/vnd.sema";
			case "semd": return "application/vnd.semd";
			case "semf": return "application/vnd.semf";
			case "see": return "application/vnd.seemail";
			case "ifm": return "application/vnd.shana.informed.formdata";
			case "itp": return "application/vnd.shana.informed.formtemplate";
			case "iif": return "application/vnd.shana.informed.interchange";
			case "ipk": return "application/vnd.shana.informed.package";
			case "slt": return "application/vnd.epson.salt";
			case "aso": return "application/vnd.accpac.simply.aso";
			case "imp": return "application/vnd.accpac.simply.imp";
			case "twd": return "application/vnd.simtech-mindmapper";
			case "csp": return "application/vnd.commonspace";
			case "saf": return "application/vnd.yamaha.smaf-audio";
			case "mmf": return "application/vnd.smaf";
			case "spf": return "application/vnd.yamaha.smaf-phrase";
			case "teacher": return "application/vnd.smart.teacher";
			case "svd": return "application/vnd.svd";
			case "skp": return "application/vnd.koan";
			case "sdc": return "application/vnd.stardivision.calc";
			case "sda": return "application/vnd.stardivision.draw";
			case "sdd": return "application/vnd.stardivision.impress";
			case "smf": return "application/vnd.stardivision.math";
			case "sdw": return "application/vnd.stardivision.writer";
			case "sgl": return "application/vnd.stardivision.writer-global";
			case "sm": return "application/vnd.stepmania.stepchart";
			case "sdkm": return "application/vnd.solent.sdkm+xml";
			case "xo": return "application/vnd.olpc-sugar";
			case "wqd": return "application/vnd.wqd";
			case "sis": return "application/vnd.symbian.install";
			case "xsm": return "application/vnd.syncml+xml";
			case "bdm": return "application/vnd.syncml.dm+wbxml";
			case "xdm": return "application/vnd.syncml.dm+xml";
			case "tao": return "application/vnd.tao.intent-module-archive";
			case "dxp": return "application/vnd.spotfire.dxp";
			case "sfs": return "application/vnd.spotfire.sfs";
			case "tpt": return "application/vnd.trid.tpt";
			case "mxs": return "application/vnd.triscape.mxs";
			case "tra": return "application/vnd.trueapp";
			case "umj": return "application/vnd.umajin";
			case "uoml": return "application/vnd.uoml+xml";
			case "unityweb": return "application/vnd.unity";
			case "ufd": return "application/vnd.ufdl";
			case "utz": return "application/vnd.uiq.theme";
			case "vsf": return "application/vnd.vsf";
			case "vcx": return "application/vnd.vcx";
			case "vis": return "application/vnd.visionary";
			case "wbxml": return "application/vnd.wap.wbxml";
			case "wtb": return "application/vnd.webturbo";
			case "wmlsc": return "application/vnd.wap.wmlscriptc";
			case "wpd": return "application/vnd.wordperfect";
			case "stf": return "application/vnd.wt.stf";
			case "xul": return "application/vnd.mozilla.xul+xml";
			case "zir": return "application/vnd.zul";
			case "zmm": return "application/vnd.handheld-entertainment+xml";
			case "zaz": return "application/vnd.zzazz.deck+xml";
		}

		return false;
	}
}